### ISSUE TITLE
How to iterate over the variables and/or constraints of a linear model

### ISSUE THREAD

**Issue by ghproek** [ykrist/rust-grb#8]
Is there a simple way to get an iterator that runs over variables and the constraints of a model?  Thanks!

**Comment by ykrist** [comment]
You can use [`Model::get_vars`](https://docs.rs/grb/latest/grb/struct.Model.html#method.get_vars) for variables  `Model::get_constrs` for linear constraints.

**Comment by ghproek** [comment]
Thank you!
